#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0

#define FAILED_TO_ALLOCATE_MEMORY 1

#define FAILED_TO_READ_NUMBER_OF_ELEM 2
#define NEGATIVE_NUMBER_OF_ELEM 3

#define FAILED_TO_READ_ELEM_OF_GRAPH 4
#define INCORRECT_GRAPH_ITEM 5

#define FILE_OPENING_ERROR 6
#define FILE_CLOSING_ERROR 7

#define FAILED_TO_READ_COMMAND_NUMBER 8
#define WRONG_COMMAND_NUMBER 9

#endif
