#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0

#define FAILED_TO_READ_COMMAND_NUMBER 1
#define WRONG_COMMAND_NUMBER 2

#define FAILED_TO_READ_ADDED_ELEMENTS 3
#define NUMBER_OF_ADDED_ELEM_IS_NEGATIVE 4
#define STACK_OVERFLOW 5

#define FAILED_TO_READ_STACK_ELEMENT 6

#define FAILED_TO_READ_REMOVED_ELEMENTS 7
#define NUMBER_OF_REMOVED_ELEM_IS_NEGATIVE 8
#define TOO_MANY_REMOVABLE_ELEMENTS 9

#define FAILED_TO_READ_STACK_TYPE 10
#define WRONG_STACK_TYPE 11

#define MEMORY_ALIGNMENT_ERROR 12

#define FILE_OPEN_ERROR 13

#endif
