#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0

#define MEMORY_ALIGNMENT_ERROR 1

#define FILE_OPENING_ERROR 2
#define FILE_CLOSING_ERROR 3

#define BUFFER_OVERFLOW 4
#define FAILED_TO_READ_NUMBER 5

#define FAILED_TO_READ_COMMAND_NUMBER 6
#define WRONG_COMMAND_NUMBER 7

#define POINT_OFFSET_ERROR 8

#define NEGATIVE_NUMBER_OF_COMPARISONS 9

#define ITEM_IS_IN_FILE 10

#endif
