#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0

#define FAILED_TO_READ_COMMAND_NUMBER 1
#define WRONG_COMMAND_NUMBER 2

#define FAILED_TO_ALLOCATE_MEMORY 3
#define ERROR_NUMBER_ROWS 4
#define ERROR_NUMBER_COLUMNS 5

#define ERROR_INPUT_METHOD 6
#define ERROR_FILL_PERCENTAGE 7

#define MATRIX_READ_ERROR 8

#define ERROR_NUMBER_NON_ZERO_ELEM 9

#define VECTOR_A_ELEM_READ_ERROR 10
#define VECTOR_JA_ELEM_READ_ERROR 11
#define LINKED_LIST_ELEM_READ_ERROR 12

#define ERROR_CONVERT_LINKED_LIST 13

#define ZERO_MATRIX 100

#define ROW_NUMBER_READ_ERROR 14
#define COLUMN_NUMBER_READ_ERROR 15

#endif
